version: "3"

services:
  mongodb:
    image: "mongo:4.0.24-xenial"

  
  backend:
    environment:
      - MONGO_DB=mongodb://mongodb:27017
    build: backend
    image: backend
    ports:
      - "3000:3000"

  frontend:
    image: frontend
    build: frontend
    ports:
      - "4200:4200"